-- INSERT into RECIPE(ID, NAME, DATECREATED, ISVEG, SERVES, INSTRUCTIONS) VALUES((SELECT ISNULL(MAX(ID) + 1, 0) FROM RECIPE), 'DalBati', CURRENT_TIMESTAMP(), true, 2, 'make');
--INSERT into INGREDIENTS(ID, RECIPE, NAME) VALUES((SELECT ISNULL(MAX(ID) + 1, 0) FROM INGREDIENTS), 1,'int1');
SELECT count(*) FROM RECIPE;